---
labels:
  version: latest
  runtime: nginx
service:
  type: ClusterIP
  port: 8080
ports:
  name: 8080-tcp
  containerPort: 8080
  protocol: TCP
resources:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

global:
  volumeMounts:
    mountPath: /var/www/html
    subPath: ""
    name: limesurvey-data
  pvc:
    php:
      size: 500Mi
    postgres:
      size: 500Mi
  licensePlate: cd77be
  sectionTag: -dev
  replicaCount: 1
  image:
    repository: image-registry.openshift-image-registry.svc:5000/
    imageStreamTag: latest
  host: "deseng-limesurvey-dev.apps.silver.devops.gov.bc.ca"

  vault:
    enabled: true
    namespace: platform-services
    authPath: "auth/k8s-silver"
    serviceAccount: cd77be-vault
